dist: xenial
os: linux
language: php
php: "7.3"
script:
  - ".travis-build/phplint ."

jobs:
  include:
  - language: node_js
    node_js: 16

before_install:
- npm i -g npm@v8.1.2
install:
- npm install
after_success:
- npm run build
- rm -rf node_modules
- tar -czf triptrack.tar.gz *
deploy:
  provider: releases
  skip_cleanup: true
   file: triptrack.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/triptrack
    branch: master
    tags: true
