dist: xenial
os: linux
language: php
php: '7.3'
script:
- ".travis-build/phplint ."
jobs:
  include:
  - language: node_js
    node_js: 16
before_install:
- npm i -g npm@v8.1.2
install:
- npm install
after_success:
- npm run build
- rm -rf node_modules
- tar -czf triptrack.tar.gz *
deploy:
  provider: releases
  skip_cleanup: true
  file: triptrack.tar.gz
  overwrite: true
  on:
    repo: AppStateESS/triptrack
    branch: master
    tags: true
  api_key:
    secure: OaVa+QjIspzutIVbUBPvxbKA7nFoHWGv/LYdOpGI5+pFdoIT1912XQMe+fksO1KqZkw9UfhuC5frUmpKl4vFIhlMC67TOXTyZlx0jqNlJc53fkHGUDoHtFh9EnK/9kWUOz/hVwqs27yd2CnvyDJvKRMlCMcX1w4wqiYMIslumBCOcAww906L26mNiXsyJUbrJfO9T7toJKg85frvdp8wlH0l7/VUObEytZm+fP2J4MnFmTmtNWREY7fzrVBfeyNwW4hcXpEW5KxljWKoqMZffDhPqcpL+czUV9IZMKnGwhKjcKl6Civb1kYxaI5ODTXlQrtPrS/ee91UtcrBcgnR0P/pCNW5PXrriP1JQwi60KyI1WEjCUJCVq3cmXVVjGBWsAbrT1Vy5zFfg9qzO4zfL6yKx7m074diSe1MwT2YTVfFv7dF011i80Ovz7Bl8Gy7jQe4+yVldAb0IJBq1CjbPjGIkL7RlHRATUbTBiYE2MrrV+abk46f4EPL1GMCjX68qtnzDOolsBrr0sF9rEtWTj49A2du402WWouvv+LsUCS9hq0emM93G04ho7w0fOQOGuwJK6m1kCjvCBfbKJRBF9R4Iz9olbso00jo3SkmRKUW23LcvW0tNVtL/RhE/ouOrBZ0g03WZ1iVWDpV3ChsFTD8PP/ORbcZ8hu5b7VXlzI=
